[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "M2S2_demo"
version = "0.1.0"
description = "Multiscale Multi-species Spatial Signatures"
license = "MIT"
requires-python = ">=3.13"
authors = [
    { name = "Abhinav Natarajan", email = "abhinav.v.natarajan@gmail.com" },
]
dependencies = [
    "chalc~=14.0.0",
    "tqdm~=4.66",
    "gudhi~=3.10",
    "scikit-tda~=1.0",
    "scikit-learn~=1.8",
    "scipy~=1.14",
    "jupyterlab~=4.2",
    "ipywidgets~=8.1",
    "shapely~=2.0",
    "pyarrow~=20.0",
    "tables~=3.10",
    "ipykernel~=6.29.5",
    "ipympl~=0.9",
    "polars>=1.43.2",
]

[tool.setuptools]
packages = ["utils"]

[tool.ruff]
line-length = 100

[tool.ruff.format]
indent-style = "tab"
docstring-code-format = true
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["ALL"]
ignore = [
	# General
	"CPY",     # flake8-copyright/missing-copyright-notice: requires cpyright notices within each Python file
	"ERA",     # eradicate: disallows commented code
	"W191",    # pycodestyle/tab-indentation: disallows tab indentation
	"D206",    # pydocstyle/docstring-tab-indentation: disallows tab indentation in docstring
	"E111",    # pycodestyle/indentation-with-invalid-multiple: forces indentation to be a multiple of 4 spaces
	"E114",    # pycodestyle/indentation-with-invalid-multiple-comment: same as above for comments
	"E117",    # pycodestyle/over-indented: disallows more than 4 spaces of indentation
	"D203",    # pydocstyle/incorrect-blank-line-before-class: requires blank line before class docstring
	"PLR0913", # pylint/too-many-arguments: too many arguments in function signature
	"PYI021",  # flake8-pyi/docstring-in-stub: disallows docstrings in stub files (not good for extension modules)
	"TD003",   # flake8-todos/missing-todo-link: disallows todos without an issue link
	"ANN401",  # flake8-annotations/any-type: disallows type 'Any' in function signatures
	"ANN003",  # flake8-annotations/missing-type-kwargs: disallows missing types for keyword args dictionary
	"FIX002",  # flake8-fixme/line-contains-todo: checks for TODO comments
	# Project-specific
	"D105", # pydocstyle/undocumented-magic-method: disallows undocumented dunder methods
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = true

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
split-on-trailing-comma = false
